data: /workspace/SSL-Backdoor/data/CIFAR10/sorted_trainset.txt
dataset: cifar10
save_poisons: True

sensitive_classes:
  - 0
attack_target_list:
  - 0
trigger_path_list:
  - /workspace/SSL-Backdoor/poison-generation/triggers/trigger_14.png
reference_dataset_file_list:
  - /workspace/SSL-Backdoor/data/CIFAR10/sorted_trainset.txt
num_poison_list:
  - 2500
num_reference_list:
  - 1200

shadow_filelist_path: /workspace/SSL-Backdoor/data/CIFAR10/sorted_trainset.txt
num_shadow: 40000
trigger_size: 8
attack_target_word: n01558993
trigger_insert: patch
finetuning_dataset: /workspace/SSL-Backdoor/data/CIFAR10/10percent_trainset.txt
downstream_dataset: /workspace/SSL-Backdoor/data/CIFAR10/testset.txt