data: /workspace/sync/SSL-Backdoor/data/CIFAR10/sorted_trainset.txt
dataset: cifar10
save_poisons: True

attack_target: 1
attack_target_word: n01558993
poison_injection_rate: 0.05
trigger_path: /workspace/sync/SSL-Backdoor/poison-generation/triggers/trigger_15.png
blend: False
trigger_size: 8

downstream_data: /workspace/sync/SSL-Backdoor/data/ImageNet-100/ImageNet100_valset.txt
targeted_idx: 0
targeted_label: