data: /workspace/sync/SSL-Backdoor/data/CIFAR10/sorted_trainset.txt
dataset: cifar10
save_poisons: True

attack_target_list:
  - 0
trigger_path_list:
  - /workspace/sync/SSL-Backdoor/poison-generation/triggers/trigger_14.png
reference_dataset_file_list:
  - /workspace/sync/SSL-Backdoor/data/CIFAR10/sorted_trainset.txt
num_poisons_list:
  - 500
if_target_from_other_dataset: False

trigger_size: 8
attack_target_word: airplane
trigger_insert: patch

finetuning_dataset: /workspace/sync/SSL-Backdoor/data/CIFAR10/10percent_trainset.txt
downstream_dataset: /workspace/sync/SSL-Backdoor/data/CIFAR10/testset.txt