attack_algorithm: sslbkd
data: data/CIFAR10/trainset.txt
dataset: cifar10
save_poisons: True

keep_poison_class: False
attack_target_list:
  - 0
trigger_path_list:
  - assets/triggers/trigger_14.png
reference_dataset_file_list:
  - data/CIFAR10/trainset.txt
num_reference_list:
  - 2500
num_poison_list:
  - 2500

attack_target_word: n01558993
trigger_insert: patch
trigger_size: 8


# testset parameters
test_train_file: data/CIFAR10/10percent_trainset.txt
test_val_file: data/CIFAR10/testset.txt
test_attack_target: 0
test_trigger_path: assets/triggers/trigger_14.png
test_dataset: cifar10
test_trigger_size: 8
test_trigger_insert: patch
test_attack_algorithm: sslbkd
test_return_attack_target: False

